M48
; DRILL file {KiCad 7.0.9} date Mon Feb 19 11:33:05 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-19T11:33:05-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T2
X7.5433Y-4.563
T1
G00X7.7165Y-4.5728
M15
G01X7.7165Y-4.5531
M16
G05
T0
M30
